spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LayJustDoIt/config-repo.git
          username: 1074870173@qq.com
          password: lsw960701
          basedir: I:\Intellij Idea\idea workspace\SpringCloud\config\basedir
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/
#      defaultZone: http://localhost:8761/eureka/
  # eureka status 显示ip
  instance:
    prefer-ip-address: true
    instance-id: config:8080